steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cocotola-www:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/cocotola-www:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git config --global user.email "cloudbuild@kujilabo.com"
        git config --global user.email "cloudbuild"

  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - --recurse-submodules
      - git@github.com:kujilabo/kujilabo-manifests.git
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - checkout
      - master

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/cocotola-www/overlays/production"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-www/overlays/production"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/cocotola/cocotola-www=gcr.io/$PROJECT_ID/cocotola-www:$SHORT_SHA"
    env:
      - "APPLY=false"
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cocotola-001'
      - 'GCLOUD_PROJECT=cocotola-001'

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - add
      - .

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - commit
      - -m
      - "Update $SHORT_SHA"

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - push
      - origin
      - master
    volumes:
      - name: "ssh"
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_deploy_key/versions/latest
      env: 'SSH_KEY'
images:
  - "gcr.io/$PROJECT_ID/cocotola-www"
