---
on: [pull_request]
name: Reviewdog
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{ts,tsx}'
          fail_on_error: true

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          locale: 'US'
          fail_on_error: true

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          yamllint_flags: '-c .github/.yamllint.yml .'
          fail_on_error: true
